export const data = [
  {
    q: "You are your best thing.",
    a: "Toni Morrison",
    c: "24",
    h: "<blockquote>&ldquo;You are your best thing.&rdquo; &mdash; <footer>Toni Morrison</footer></blockquote>",
  },
  {
    q: "Faults are yours to fix, not to curse.",
    a: "Colin Powell",
    c: "38",
    h: "<blockquote>&ldquo;Faults are yours to fix, not to curse.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>",
  },
  {
    q: "All know that the drop merges into the ocean, but few know that the ocean merges into the drop.",
    a: "Kabir",
    c: "95",
    h: "<blockquote>&ldquo;All know that the drop merges into the ocean, but few know that the ocean merges into the drop.&rdquo; &mdash; <footer>Kabir</footer></blockquote>",
  },
  {
    q: "Happiness is pretty simple: someone to love, something to do, something to look forward to.",
    a: "Rita Mae Brown",
    c: "91",
    h: "<blockquote>&ldquo;Happiness is pretty simple: someone to love, something to do, something to look forward to.&rdquo; &mdash; <footer>Rita Mae Brown</footer></blockquote>",
  },
  {
    q: "Saying nothing sometimes says the most.",
    a: "Emily Dickinson",
    c: "39",
    h: "<blockquote>&ldquo;Saying nothing sometimes says the most.&rdquo; &mdash; <footer>Emily Dickinson</footer></blockquote>",
  },
  {
    q: "It all depends on what you choose to believe.",
    a: "Spencer Johnson",
    c: "45",
    h: "<blockquote>&ldquo;It all depends on what you choose to believe.&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "I cannot make my days longer so I strive to make them better.",
    a: "Henry David Thoreau",
    c: "61",
    h: "<blockquote>&ldquo;I cannot make my days longer so I strive to make them better.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "It only takes a split second to smile and forget, yet to someone that needed it, it can last a lifetime.",
    a: "Steve Maraboli",
    c: "104",
    h: "<blockquote>&ldquo;It only takes a split second to smile and forget, yet to someone that needed it, it can last a lifetime.&rdquo; &mdash; <footer>Steve Maraboli</footer></blockquote>",
  },
  {
    q: "Always look on the bright side of things. If you can't comprehend this, polish that which has become dull until it begins to shine.",
    a: "Zen Proverb",
    c: "131",
    h: "<blockquote>&ldquo;Always look on the bright side of things. If you can't comprehend this, polish that which has become dull until it begins to shine.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "If there were no God, there would be no atheists.",
    a: "Gilbert Chesterton",
    c: "49",
    h: "<blockquote>&ldquo;If there were no God, there would be no atheists.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "Never regret your past. Rather, embrace it as the teacher that it is.",
    a: "Robin Sharma",
    c: "69",
    h: "<blockquote>&ldquo;Never regret your past. Rather, embrace it as the teacher that it is.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Life becomes easier and more beautiful when we can see the good in other people.",
    a: "Roy T. Bennett",
    c: "80",
    h: "<blockquote>&ldquo;Life becomes easier and more beautiful when we can see the good in other people.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Follow the man who seeks the truth; run from the man who has found it.",
    a: "Vaclav Havel",
    c: "70",
    h: "<blockquote>&ldquo;Follow the man who seeks the truth; run from the man who has found it.&rdquo; &mdash; <footer>Vaclav Havel</footer></blockquote>",
  },
  {
    q: "Always seek out the seed of triumph in every adversity.",
    a: "Og Mandino",
    c: "55",
    h: "<blockquote>&ldquo;Always seek out the seed of triumph in every adversity.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Try to be a rainbow in someone's cloud.",
    a: "Maya Angelou",
    c: "39",
    h: "<blockquote>&ldquo;Try to be a rainbow in someone's cloud.&rdquo; &mdash; <footer>Maya Angelou</footer></blockquote>",
  },
  {
    q: "When you are talented you do it whatever it is until your fingers bleed or your eyes are ready to fall out of your head.",
    a: "Stephen King",
    c: "120",
    h: "<blockquote>&ldquo;When you are talented you do it whatever it is until your fingers bleed or your eyes are ready to fall out of your head.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "Information changes your mind. Action changes your circumstances.",
    a: "Jack Butcher",
    c: "65",
    h: "<blockquote>&ldquo;Information changes your mind. Action changes your circumstances.&rdquo; &mdash; <footer>Jack Butcher</footer></blockquote>",
  },
  {
    q: "I have no methods; all I do is accept people as they are.",
    a: "Joan Rivers",
    c: "57",
    h: "<blockquote>&ldquo;I have no methods; all I do is accept people as they are.&rdquo; &mdash; <footer>Joan Rivers</footer></blockquote>",
  },
  {
    q: "The sun shines upon good and bad alike.",
    a: "Hans Christian Andersen",
    c: "39",
    h: "<blockquote>&ldquo;The sun shines upon good and bad alike.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "I was wise enough to never grow up while fooling most people into believing I had. ",
    a: "Margaret Mead",
    c: "83",
    h: "<blockquote>&ldquo;I was wise enough to never grow up while fooling most people into believing I had. &rdquo; &mdash; <footer>Margaret Mead</footer></blockquote>",
  },
  {
    q: "Where words fail, music speaks.",
    a: "Hans Christian Andersen",
    c: "31",
    h: "<blockquote>&ldquo;Where words fail, music speaks.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "Through discipline comes freedom.",
    a: "Aristotle",
    c: "33",
    h: "<blockquote>&ldquo;Through discipline comes freedom.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "A random act of kindness, no matter how small, can make a tremendous impact on someone else's life.",
    a: "Roy T. Bennett",
    c: "99",
    h: "<blockquote>&ldquo;A random act of kindness, no matter how small, can make a tremendous impact on someone else's life.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "If you spend too much time thinking about a thing, you'll never get it done. ",
    a: "Bruce Lee",
    c: "77",
    h: "<blockquote>&ldquo;If you spend too much time thinking about a thing, you'll never get it done. &rdquo; &mdash; <footer>Bruce Lee</footer></blockquote>",
  },
  {
    q: "To get angry is like to revenge yourself for the guilt of others.",
    a: "Jonathan Swift",
    c: "65",
    h: "<blockquote>&ldquo;To get angry is like to revenge yourself for the guilt of others.&rdquo; &mdash; <footer>Jonathan Swift</footer></blockquote>",
  },
  {
    q: "The truly rich men are the ones who have health, loved ones and a work they love.",
    a: "Maxime Lagace",
    c: "81",
    h: "<blockquote>&ldquo;The truly rich men are the ones who have health, loved ones and a work they love.&rdquo; &mdash; <footer>Maxime Lagace</footer></blockquote>",
  },
  {
    q: "New beginnings are disguised as painful endings.",
    a: "Lao Tzu",
    c: "48",
    h: "<blockquote>&ldquo;New beginnings are disguised as painful endings.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "You have as much laughter as you have faith.",
    a: "Martin Luther",
    c: "44",
    h: "<blockquote>&ldquo;You have as much laughter as you have faith.&rdquo; &mdash; <footer>Martin Luther</footer></blockquote>",
  },
  {
    q: "Anything worth doing is worth doing slowly.",
    a: "Mae West",
    c: "43",
    h: "<blockquote>&ldquo;Anything worth doing is worth doing slowly.&rdquo; &mdash; <footer>Mae West</footer></blockquote>",
  },
  {
    q: "Everything eaten is killed. Every meal is a sacrifice.",
    a: "Adi Da Samraj",
    c: "54",
    h: "<blockquote>&ldquo;Everything eaten is killed. Every meal is a sacrifice.&rdquo; &mdash; <footer>Adi Da Samraj</footer></blockquote>",
  },
  {
    q: "From morning till night, we should never rely on a single thing.",
    a: "Huang Po",
    c: "64",
    h: "<blockquote>&ldquo;From morning till night, we should never rely on a single thing.&rdquo; &mdash; <footer>Huang Po</footer></blockquote>",
  },
  {
    q: "Sometimes you have to travel a long way to find what is near.",
    a: "Paulo Coelho",
    c: "61",
    h: "<blockquote>&ldquo;Sometimes you have to travel a long way to find what is near.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "The score never interested me, only the game.",
    a: "Mae West",
    c: "45",
    h: "<blockquote>&ldquo;The score never interested me, only the game.&rdquo; &mdash; <footer>Mae West</footer></blockquote>",
  },
  {
    q: "I am not proud, but I am happy; and happiness blinds, I think, more than pride.",
    a: "Alexandre Dumas",
    c: "79",
    h: "<blockquote>&ldquo;I am not proud, but I am happy; and happiness blinds, I think, more than pride.&rdquo; &mdash; <footer>Alexandre Dumas</footer></blockquote>",
  },
  {
    q: "Before you speak, ask yourself, is it kind, is it necessary, is it true, does it improve the silence?",
    a: "Sathya Sai Baba",
    c: "101",
    h: "<blockquote>&ldquo;Before you speak, ask yourself, is it kind, is it necessary, is it true, does it improve the silence?&rdquo; &mdash; <footer>Sathya Sai Baba</footer></blockquote>",
  },
  {
    q: "Do not regret the past. Look to the future.",
    a: "Soyen Shaku",
    c: "43",
    h: "<blockquote>&ldquo;Do not regret the past. Look to the future.&rdquo; &mdash; <footer>Soyen Shaku</footer></blockquote>",
  },
  {
    q: "The more acquaintances you have, the less you know them.",
    a: "Chinese Proverb",
    c: "56",
    h: "<blockquote>&ldquo;The more acquaintances you have, the less you know them.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "He who knows how to wait need make no concessions.",
    a: "Sigmund Freud",
    c: "50",
    h: "<blockquote>&ldquo;He who knows how to wait need make no concessions.&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "Live the moment for the moment.",
    a: "Michael Jordan",
    c: "31",
    h: "<blockquote>&ldquo;Live the moment for the moment.&rdquo; &mdash; <footer>Michael Jordan</footer></blockquote>",
  },
  {
    q: "Quality means doing it right when no one is looking.",
    a: "Henry Ford",
    c: "52",
    h: "<blockquote>&ldquo;Quality means doing it right when no one is looking.&rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "Every day do something that will inch you closer to a better tomorrow.",
    a: "Unknown",
    c: "70",
    h: "<blockquote>&ldquo;Every day do something that will inch you closer to a better tomorrow.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "It is up to each of us to sing as we feel moved by the overall song of life.",
    a: "Ming-Dao Deng",
    c: "76",
    h: "<blockquote>&ldquo;It is up to each of us to sing as we feel moved by the overall song of life.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Do not wait for leaders; do it alone, person to person.",
    a: "Mother Teresa",
    c: "55",
    h: "<blockquote>&ldquo;Do not wait for leaders; do it alone, person to person.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: "Life can only be understood backwards; but it must be lived forwards.",
    a: "Soren Kierkegaard",
    c: "69",
    h: "<blockquote>&ldquo;Life can only be understood backwards; but it must be lived forwards.&rdquo; &mdash; <footer>Soren Kierkegaard</footer></blockquote>",
  },
  {
    q: "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Your life will never be the same again.",
    a: "Og Mandino",
    c: "126",
    h: "<blockquote>&ldquo;Beginning today, treat everyone you meet as if they were going to be dead by midnight. Your life will never be the same again.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Weeds are flowers too, once you get to know them.",
    a: "A.A. Milne",
    c: "49",
    h: "<blockquote>&ldquo;Weeds are flowers too, once you get to know them.&rdquo; &mdash; <footer>A.A. Milne</footer></blockquote>",
  },
  {
    q: "Life without love is like a tree without blossoms or fruit.",
    a: "Kahlil Gibran",
    c: "59",
    h: "<blockquote>&ldquo;Life without love is like a tree without blossoms or fruit.&rdquo; &mdash; <footer>Kahlil Gibran</footer></blockquote>",
  },
  {
    q: "Making money isn't hard in itself... What's hard is to earn it doing something worth devoting one's life to.",
    a: "Carlos Ruiz Zafon",
    c: "108",
    h: "<blockquote>&ldquo;Making money isn't hard in itself... What's hard is to earn it doing something worth devoting one's life to.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "The best of us sometimes eat our words.  ",
    a: "Albus Dumbledore",
    c: "41",
    h: "<blockquote>&ldquo;The best of us sometimes eat our words.  &rdquo; &mdash; <footer>Albus Dumbledore</footer></blockquote>",
  },
  {
    q: "I am always doing that which I can not do, in order that I may learn how to do it.",
    a: "Pablo Picasso",
    c: "82",
    h: "<blockquote>&ldquo;I am always doing that which I can not do, in order that I may learn how to do it.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
];
